final concerts = [
  {
    'id': '0',
    'title': 'Sunburn Goa, 2025',
    'price': 40.0,
    'imageUrl': 'assets/images/sunburn_2025.jpg',
    'category': 'Edm',
    'quantity': [1, 2, 3, 4],
  },
  {
    'id': '1',
    'title': 'Bangr Festival, CHD',
    'price': 20.0,
    'imageUrl': 'assets/images/bangr_fest.jpg',
    'category': 'Music',
    'quantity': [1, 2, 3, 4],
  },
  {
    'id': '2',
    'title': 'Lollapalooza India,\n2025',
    'price': 30.0,
    'imageUrl': 'assets/images/lollapalooza_india.jpg',
    'category': 'Edm',
    'quantity': [1, 2, 3, 4],
  },
  {
    'id': '3',
    'title': 'Cigarettes After Sex,\n India ',
    'price': 35.0,
    'imageUrl': 'assets/images/cas_india.jpg',
    'category': 'Edm',
    'quantity': [1, 2, 3, 4],
  },
  {
    'id': '4',
    'title': 'Coldplay India, 2025',
    'price': 50.0,
    'imageUrl': 'assets/images/coldplay_india_2025.jpg',
    'category': 'Edm',
    'quantity': [1, 2, 3, 4],
  },
];
